### ISSUE TITLE
LEYPA CONTRACT LIBRARIES

### ISSUE THREAD

**Issue by 0zAND1z** [KIPFoundation/kide-web#1]
- [ ] Offchain Storage APIs
- [ ] Tokenization APIs (WRC20)
- [ ] Identity APIs
- [ ] Cognitive APIs (result matching)
